spring:
  mvc:
    view:
      prefix: /
      suffix:
  datasource:
    url: jdbc:mysql://localhost:3306/JIHAOSHI?useUnicode=yes&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Taipei
    username: root
    password: password